[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https:; connect-src 'self' https://api.roblox.com https://ip-api.com; frame-src 'self' https://discord.com;"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Keep localized URLs canonical; no forced 301 from /:lang/*
# If needed, you can add soft rewrites later.

# Keep existing SPA rewrite last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: reduce indexing of param variants if any are used
[[headers]]
  for = "/guides.html?lang=*"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

[[headers]]
  for = "/index.html?lang=*"
  [headers.values]
    X-Robots-Tag = "noindex, follow"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview" 